In [2]:
#Series
import pandas as pd
import numpy as np

s1 = pd.Series([10, 20, 30, 40]) #default integer index
s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd']) #custom index
s3 = pd.Series({'Math': 95, 'Biology': 68, 'Social Science': 88, 'English': 95}) #from dict

print("Default index Series:\n:", s1)
print("\nCustom index series:\n", s2)
print("\nSeries from dict:\n", s3)

Default index Series:
: 0    10
1    20
2    30
3    40
dtype: int64

Custom index series:
 a    10
b    20
c    30
d    40
dtype: int64

Series from dict:
 Math              95
Biology           68
Social Science    88
English           95
dtype: int64

In [3]:
#Acessing elements
print(f"\nAccess s2['b']: {s2['b']}")
print(f"\nAccess s2.iloc[1]: {s2.iloc[1]}")
print(f"\nAccess s3['Maths']: {s3['Math']}")

Access s2['b']: 20

Access s2.iloc[1]: 20

Access s3['Maths']: 95

In [5]:
#Series operations (vectorized automatically)
print("\ns2 * 2:\n", s2 * 2)
print("\ns2 > 15\n", s2 > 15)
print("\nFiltered s2:\n",s2[s2>15])

s2 * 2:
 a    20
b    40
c    60
d    80
dtype: int64

s2 > 15
 a    False
b     True
c     True
d     True
dtype: bool

Filtered s2:
 b    20
c    30
d    40
dtype: int64

In [6]:
#useful series attributes
print("\nValues:", s2.values)
print("Index:", s2.index.tolist())
print("dtype:", s2.dtype)
print("shape", s2.shape)

Values: [10 20 30 40]
Index: ['a', 'b', 'c', 'd']
dtype: int64
shape (4,)

In [9]:
#DataFrame Creation and Exploration
#DataFrame: 2D table like an excel sheet
#Each column is a series sharing the same index
data = {
    'Name':   ['Asha', 'Ravi', 'Meena', 'Karan', 'Priya'],
    'Age':    [22, 25, 23, 28, 24],
    'City':   ['Bangalore', 'Mumbai', 'Delhi', 'Bangalore', 'Chennai'],
    'Marks':  [88, 92, 79, 95, 84],
    'Course': ['CS', 'MBA', 'CS', 'MBA', 'CS']
}
df = pd.DataFrame(data)
df

    Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
1   Ravi   25     Mumbai     92    MBA
2  Meena   23      Delhi     79     CS
3  Karan   28  Bangalore     95    MBA
4  Priya   24    Chennai     84     CS

In [15]:
#Exploration methods
print(f'\nShape (rows, columns): {df.shape}')
print(f'\nColumn names: {df.columns.tolist()}')
print(f'\nData types:\n{df.dtypes}')
print(f'\nDescribe (stats from numeric columns):\n{df.describe()}')
print(f'\nHead (first 2 rows): \n{df.head(2)}')
print(f'\nTail (last 2 rows): \n{df.tail(2)}')
print(f'\nInfo: \n{df.info}')
print(f'\nNull check:\n {df.isnull().sum()}')
print(f'\nCheck unique values in Course column: \n{df['Course'].value_counts()}')

Shape (rows, columns): (5, 5)

Column names: ['Name', 'Age', 'City', 'Marks', 'Course']

Data types:
Name      object
Age        int64
City      object
Marks      int64
Course    object
dtype: object

Describe (stats from numeric columns):
             Age      Marks
count   5.000000   5.000000
mean   24.400000  87.600000
std     2.302173   6.348228
min    22.000000  79.000000
25%    23.000000  84.000000
50%    24.000000  88.000000
75%    25.000000  92.000000
max    28.000000  95.000000

Head (first 2 rows):
   Name  Age       City  Marks Course
0  Asha   22  Bangalore     88     CS
1  Ravi   25     Mumbai     92    MBA

Tail (last 2 rows):
    Name  Age       City  Marks Course
3  Karan   28  Bangalore     95    MBA
4  Priya   24    Chennai     84     CS

Info:
<bound method DataFrame.info of     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
1   Ravi   25     Mumbai     92    MBA
2  Meena   23      Delhi     79     CS
3  Karan   28  Bangalore     95    MBA
4  Priya   24    Chennai     84     CS>

Null check:
 Name      0
Age       0
City      0
Marks     0
Course    0
dtype: int64

Check unique values in Course column:
Course
CS     3
MBA    2
Name: count, dtype: int64

In [16]:
#key distinction
#loc: label based: uses actual index labels and column Names
#iloc: position-based: uses integer positions (like NumPy 0,1,2...)
df = pd.DataFrame({
    'Name':   ['Asha', 'Ravi', 'Meena', 'Karan', 'Priya'],
    'Age':    [22, 25, 23, 28, 24],
    'City':   ['Bangalore', 'Mumbai', 'Delhi', 'Bangalore', 'Chennai'],
    'Marks':  [88, 92, 79, 95, 84],
    'Course': ['CS', 'MBA', 'CS', 'MBA', 'CS']
}, index = [10, 20, 30, 40, 50])   # custom index to show the difference clearly

print(f'DataFrame with custom index: \n', df)

DataFrame with custom index:
      Name  Age       City  Marks Course
10   Asha   22  Bangalore     88     CS
20   Ravi   25     Mumbai     92    MBA
30  Meena   23      Delhi     79     CS
40  Karan   28  Bangalore     95    MBA
50  Priya   24    Chennai     84     CS

In [19]:
#loc
print('#loc')
print(f'\nSingle row (index=10):\n {df.loc[10]}')
print(f'\nSingle cell: {df.loc[10, 'Name']}')
print(f'\nRow range 10-30, cols Name & Marks:\n {df.loc[10:30, ['Name', 'Marks']]}')
print(f'\nAll rows, 2 columns:\n {df.loc[:, ['Name', 'City']]}')

#loc

Single row (index=10):
 Name           Asha
Age              22
City      Bangalore
Marks            88
Course           CS
Name: 10, dtype: object

Single cell: Asha

Row range 10-30, cols Name & Marks:
      Name  Marks
10   Asha     88
20   Ravi     92
30  Meena     79

All rows, 2 columns:
      Name       City
10   Asha  Bangalore
20   Ravi     Mumbai
30  Meena      Delhi
40  Karan  Bangalore
50  Priya    Chennai

In [20]:
#iloc
print('#iloc')
print(f'\nFirst row (position 0):\n {df.iloc[0]}')
print(f'\nSingle cell (row:0, col:0): {df.iloc[0, 0]}')
print("\nRows 0-2, cols 0-1:\n", df.iloc[0:3, 0:2])                 # note: 0:3 is EXCLUSIVE (like Python slicing)
print("\nLast row:\n", df.iloc[-1])
print("\nEvery other row:\n", df.iloc[::2])

#iloc

First row (position 0):
 Name           Asha
Age              22
City      Bangalore
Marks            88
Course           CS
Name: 10, dtype: object

Single cell (row:0, col:0): Asha

Rows 0-2, cols 0-1:
      Name  Age
10   Asha   22
20   Ravi   25
30  Meena   23

Last row:
 Name        Priya
Age            24
City      Chennai
Marks          84
Course         CS
Name: 50, dtype: object

Every other row:
      Name  Age       City  Marks Course
10   Asha   22  Bangalore     88     CS
30  Meena   23      Delhi     79     CS
50  Priya   24    Chennai     84     CS

In [23]:
# With default index (0,1,2...) loc and iloc feel the same
# but with custom index (10,20,30...) they differ:
print("\nloc[10]: row with INDEX LABEL 10:", df.loc[10, 'Name'])    # Asha
print("\niloc[0]: row at POSITION 0:", df.iloc[0]['Name'])            # also Asha, but for different reason
print("\niloc[10]: would throw IndexError (only 5 rows!)")

loc[10]: row with INDEX LABEL 10: Asha

iloc[0]: row at POSITION 0: Asha

iloc[10]: would throw IndexError (only 5 rows!)

In [24]:
# Reset to simple index for clarity
df = pd.DataFrame({
    'Name':   ['Asha', 'Ravi', 'Meena', 'Karan', 'Priya'],
    'Age':    [22, 25, 23, 28, 24],
    'City':   ['Bangalore', 'Mumbai', 'Delhi', 'Bangalore', 'Chennai'],
    'Marks':  [88, 92, 79, 95, 84],
    'Course': ['CS', 'MBA', 'CS', 'MBA', 'CS']
})

# --- Single condition ---
print("Marks > 85:\n", df[df['Marks'] > 85])
print("\nCity == Bangalore:\n", df[df['City'] == 'Bangalore'])

# --- Multiple conditions ---
# & = AND, | = OR, ~ = NOT (must use these, not Python's and/or)
print("\nMarks > 80 AND City == Bangalore:\n",
      df[(df['Marks'] > 80) & (df['City'] == 'Bangalore')])

print("\nMarks > 90 OR Course == CS:\n",
      df[(df['Marks'] > 90) | (df['Course'] == 'CS')])

print("\nNOT from Delhi:\n",
      df[~(df['City'] == 'Delhi')])

# --- isin() for multiple value matching ---
print("\nCity in [Bangalore, Mumbai]:\n",
      df[df['City'].isin(['Bangalore', 'Mumbai'])])

# --- between() for range filtering ---
print("\nAge between 22 and 25:\n",
      df[df['Age'].between(22, 25)])

# --- str methods for string filtering ---
print("\nNames starting with 'A' or 'R':\n",
      df[df['Name'].str.startswith(('A', 'R'))])

# --- query() method — more readable syntax ---
print("\nUsing query():\n",
      df.query("Marks > 85 and City == 'Bangalore'"))

# --- Selecting specific columns after filter ---
print("\nNames of students with Marks > 85:\n",
      df[df['Marks'] > 85]['Name'].values)

print("\nName + Marks for Bangalore students:\n",
      df[df['City'] == 'Bangalore'][['Name', 'Marks']])

Marks > 85:
     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
1   Ravi   25     Mumbai     92    MBA
3  Karan   28  Bangalore     95    MBA

City == Bangalore:
     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
3  Karan   28  Bangalore     95    MBA

Marks > 80 AND City == Bangalore:
     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
3  Karan   28  Bangalore     95    MBA

Marks > 90 OR Course == CS:
     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
1   Ravi   25     Mumbai     92    MBA
2  Meena   23      Delhi     79     CS
3  Karan   28  Bangalore     95    MBA
4  Priya   24    Chennai     84     CS

NOT from Delhi:
     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
1   Ravi   25     Mumbai     92    MBA
3  Karan   28  Bangalore     95    MBA
4  Priya   24    Chennai     84     CS

City in [Bangalore, Mumbai]:
     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
1   Ravi   25     Mumbai     92    MBA
3  Karan   28  Bangalore     95    MBA

Age between 22 and 25:
     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
1   Ravi   25     Mumbai     92    MBA
2  Meena   23      Delhi     79     CS
4  Priya   24    Chennai     84     CS

Names starting with 'A' or 'R':
    Name  Age       City  Marks Course
0  Asha   22  Bangalore     88     CS
1  Ravi   25     Mumbai     92    MBA

Using query():
     Name  Age       City  Marks Course
0   Asha   22  Bangalore     88     CS
3  Karan   28  Bangalore     95    MBA

Names of students with Marks > 85:
 ['Asha' 'Ravi' 'Karan']

Name + Marks for Bangalore students:
     Name  Marks
0   Asha     88
3  Karan     95

In [25]:
df_netflix = pd.read_csv(r'netflix_titles.csv')
df_netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [43]:
print('Shape:', df_netflix.shape)
print('\nColumns:', df_netflix.columns.tolist())
print('\nNull check:\n', df_netflix.isnull().sum())
df_netflix.info()

Shape: (8807, 12)

Columns: ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

Null check:
 show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [44]:
movies = df_netflix[df_netflix['type'] == 'Movie']
print('Total Movies: ', len(movies))

Total Movies:  6131

In [48]:
#content release after 2015
recent = df_netflix[df_netflix['release_year'] > 2015]
print('\nReleased after 2015:',len(recent))

Released after 2015: 5656

In [50]:
#indian content
Indian_content = df_netflix[df_netflix['country'] == 'India']
print('Indian content:', len(Indian_content))

Indian content: 972

In [56]:
recent_Indian_movies = df_netflix[(df_netflix['type'] == 'Movie') & (df_netflix['country'] == 'India') & (df_netflix['release_year'] > 2015)]
print('Recent Indian movies:', len(recent_Indian_movies))
recent_Indian_movies[['title', 'release_year', 'rating']].head(10)

Recent Indian movies: 406

                            title  release_year rating
105              Angamaly Diaries          2017  TV-14
118                       Gurgaon          2017  TV-14
126                       Shikara          2020  TV-14
190                    Thimmarusu          2021  TV-14
203          Kyaa Kool Hain Hum 3          2016  TV-MA
518  Har Kisse Ke Hisse: Kaamyaab          2020  TV-14
541              Truckbhar Swapna          2018  TV-14
551               Haseen Dillruba          2021  TV-MA
735                       Sarbath          2021  TV-PG
850                      99 Songs          2021  TV-14